"""add state_json to conversation

Revision ID: 8f448ec0e4ee
Revises: 0008_user_session_scope
Create Date: 2026-09-20 03:17:12.875418+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8f448ec0e4ee'
down_revision: str | None = '0008_user_session_scope'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('state_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'state_json')
    # ### end Alembic commands ###